### ISSUE TITLE
Contributing guidelines?

### ISSUE THREAD

**Issue by phoniks** [THCLab/tool#1]
I'm super interested in ODCA and would love to help contribute to this tool.  What are some issues I could tackle to help move this project forward?

**Comment by mitfik** [comment]
I am glad that you found ODCA interesting. We are currently in progress of moving the repo into new location: https://bitbucket.org/dativa4data/odcatool/ 
Where we would continue working. Soon github repo would be read only.  All issues and milestones would be on bitbucket. So feel free to take a look on existing issues and let me know if you would like to help with any of them. Feel free to create new as well. 

So far the tools is very basic and in early stage but with some help we can get it further.
In meantime I would suggest to join Hyperledger Chat specifically semantic WG channel: https://chat.hyperledger.org/channel/indy-semantics 
Where we discussing and notifying about topics and materials related to ODCA.
